config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'
  get 'pages/about'
  get 'panel/index'

  resources :forms do
    resources :answers, only: [:new, :create, :show]  
    member do
      put :change_consent
    end
  end

  resources :questions, only: [:create, :destroy] do
    member do
      post :add_option
      delete :remove_option
    end
  end



end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :find_form, only: [:edit, :update, :show, :change_consent]

  def index
    @forms = current_user.forms.all
  end

  def show;end

  def new
    @form = current_user.forms.build
  end

  def create
    @form = current_user.forms.build(form_params)

    if @form.save
      redirect_to edit_form_path(@form, anchor: 'new-form-option-title')
    else
      render :new
    end
  end

  def edit
    @questions = @form.questions.includes(:question_options)
  end

  def update
    if @form.update_attributes(form_params)
      redirect_to (edit_form_path(@form))
    else
      @questions = @form.questions.includes(:question_options)
      render :edit
    end
  end

  def change_consent
    @form.consent = params[:consent]
    @form.save
  end

  private
    def form_params
      params.require(:form).permit(:position, :company, :location, :description)
    end

    def find_form
      @form = Form.find(params[:id])
    end
end

app/views/forms/_error.haml
- if form.errors.full_messages.any?
  .row
    .col-lg-2.col-sm-1.hidden-xs
    .col-lg-8.col-sm-10.col-xs-12
      .new-form-error-panel
        - form.errors.full_messages.each do |msg|
          = msg
          %br

app/views/forms/_option.haml
.option-for-question-list
  %br
  = option.content
  %span.span-option-delete{ data: { id: option.id, question_id: option.question_id }} x

app/views/forms/_question.haml
.question-item-list
  .button-delete-on-list
    %span{class: "span-delete-from-list", data: { id: question.id} } x
  %h4
    = question.content
  -# %h5
  -#   Pytanie Obowiązkowe:
  -#   %span.span-in-h5-in-quesion-list
  -#     = question.necessary ? "Tak" : "Nie"

  - if question.is_closed
    .question-option-list{class: "question-nr-" + question.id.to_s }
      %br
      %h5.text-add-new-option Dodaj odpowiedź do pytania:
      %input.input-option-for-question{type: "text", class: "input-for-option-nr-" + question.id.to_s }
      %button.btn.btn-primary.btn-add-option-for-question{data: { question_id: question.id } } +
      - question.question_options.each do |o|
        = render "forms/option", option: o

app/views/forms/edit.haml
= render 'forms/error', form: @form

.row
  .col-lg-12.col-sm-12.col-xs-12
    .row
      .col-lg-2.col-sm-1.hidden-xs

      .col-lg-8.col-sm-10.col-xs-12
        .container-for-form
          .new-form-title
            %h3 1. Personalizacja formularza
            %p Formularz musi zawierać podstawowe informacje:
          .new-form-form
            = form_for @form do |f|
              %h4 Nazwa firmy*
              = f.text_field :company, class: "new_form_input"
              %br
              %h4 Lokalizacja*
              = f.text_field :location, class: "new_form_input"
              %br
              %h4 Nazwa stanowiska*
              = f.text_field :position, class: "new_form_input"
              %br
              %h4
                Krótki opis
                %br
                %small maksymalnie 255 znaków
              = f.text_area :description
              %br
              .form-description-about
                %p Formularz domyślnie zawiera pola takie jak: imię, nazwisko, email, telefon, miasto, CV oraz standardowa zgoda o wykorzystywaniu danych osobowych. Będziesz miał możliwość edycji lub dodania własnych zgód czy regulaminu. W następnym kroku stworzysz pola wybrane przez siebie oraz sugerowane odpowiedzi.
              %br
              %h4 Zaaktualizuj podstawowe informacje
              = f.submit 'Zapisz', class: "btn btn-primary btn-submit-form"

          .new-form-option
            .new-form-option-title
              %br
              %h3{:id => "new-form-option-title"} 2. Dodatkowe opcje
              %h4 Wybierz rodzaj pytania, jakie dodasz do formularza:
              %p Możesz dodać pytania otwarte, takie w których aplikant udzieli swobodnej odpowiedzi. Oraz pytanie zamknięte, gdzie możliwe odpowiedzi ustalisz sam.

            .new-form-option-questions
              %br
              %h4 Treść pytania:
              %input.question-content{:type => "text"}
              %br
              %input.input-with-id-form{:type => "hidden", :value => @form.id }
              -# %h5 Dla pytań obowiązkowych, pozostaw zaznaczone:
              -# %input.is_necessary{:type => "checkbox", :checked => "true"}
              %br
              %br
              %button.question-open-button.btn.btn-primary{:value => "false"} Otwarte
              %button.question-close-button.btn.btn-primary{:value => "true"} Zamknięte

            .new-questions-list
              - @questions.each do |quest|
                = render "forms/question", question: quest
          .new-form-view-settings
            %h3 3. Wygląd formularza
            %p Wkrótce....

          .new-form-consent-setting
            %h3 4. Zgody danych osobowych i inne
            %p Aby zmienić domyślną zgodę, zapisz własną.
            %p Pamiętaj aby zgoda była zgodna z prawem i wymogami RODO.
            %textarea.form-edit-text-field-for-consent
              = @form.consent
            %br
            %button.btn.btn-primary.btn-for-consent{ data: { id: @form.id }} Zapisz zgodę

      .col-lg-2.col-sm-1.hidden-xs


- content_for :javascript do
  = javascript_include_tag 'edit-form'

- content_for :style do
  = stylesheet_link_tag 'newform', media: 'all'

app/views/forms/index.haml
%h1 form/index

- @forms.each do |f|
  %h3
    = f.position
  %h5
    = f.location
  = link_to 'edytuj', edit_form_path(f)
  = link_to 'show,', form_path(f)
  %hr

app/views/forms/new.haml
= render 'forms/error', form: @form


.row
  .col-lg-12.col-sm-12.col-xs-12
    .row
      .col-lg-2.col-sm-1.hidden-xs

      .col-lg-8.col-sm-10.col-xs-12
        .container-for-form
          .new-form-title
            %h3 Tworzenie nowego formularza dla rekrutacji
            %p Aby stworzyć nowy formularz, podaj podstawowe informacje:
          .new-form-form
            = form_for @form do |f|
              %h4 Nazwa firmy*
              = f.text_field :company, class: "new_form_input"
              %br
              %h4 Lokalizacja*
              = f.text_field :location, class: "new_form_input"
              %br
              %h4 Nazwa stanowiska*
              = f.text_field :position, class: "new_form_input"
              %br
              %h4
                Krótki opis
                %br
                %small maksymalnie 255 znaków
              = f.text_area :description
              %br
              .form-description-about
                %p Formularz domyślnie zawiera pola takie jak: imię, nazwisko, email, telefon, miasto, CV oraz standardowa zgoda o wykorzystywaniu danych osobowych. Będziesz miał możliwość edycji lub dodania własnych zgód czy regulaminu. W następnym kroku stworzysz pola wybrane przez siebie oraz sugerowane odpowiedzi.
              %br
              %h4 Aby przejść do następnego kroku
              = f.submit 'Dalej', class: "btn btn-primary btn-submit-form"
      .col-lg-2.col-sm-1.hidden-xs


- content_for :style do
  = stylesheet_link_tag 'newform', media: 'all'

app/views/forms/show.haml
%h1 Show/form
%h4
  = @form.position

= link_to "Pokaz formularz ", new_form_answer_path(@form)