config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'
  get 'pages/about'
  get 'panel/index'

  resources :forms do
    resources :answers, only: [:new, :create, :show]  
    member do
      put :change_consent
    end
  end

  resources :questions, only: [:create, :destroy] do
    member do
      post :add_option
      delete :remove_option
    end
  end



end

app/views/layouts/_menu.haml
Menu
= link_to 'logout', destroy_user_session_path, method: :delete
= link_to 'panel', panel_index_path

app/views/layouts/answer.haml
!!!
%html
  %head
    = yield :title
    = csrf_meta_tags
    = csp_meta_tag
    - if protect_against_forgery?
      %meta#authenticity-token{:content => form_authenticity_token, :name => "authenticity-token"}/
    = stylesheet_link_tag    'answer', media: 'all'
    = javascript_include_tag 'application'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.3.1/css/all.css", :integrity => "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", :rel => "stylesheet"}/
  %body
    .container-fluid
      -if user_signed_in?
        = render 'layouts/menu'
      = yield

  = yield :script

app/views/layouts/application.haml
!!!
%html
  %head
    %title CareerPath
    = csrf_meta_tags
    = csp_meta_tag
    - if protect_against_forgery?
      %meta#authenticity-token{:content => form_authenticity_token, :name => "authenticity-token"}/
    = stylesheet_link_tag    'application', media: 'all'
    = yield :style
    = javascript_include_tag 'application'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.3.1/css/all.css", :integrity => "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", :rel => "stylesheet"}/
  %body
    .container-fluid
      = render 'layouts/menu'
      = yield
    = yield :javascript

app/views/layouts/mainpage.haml
!!!
%html
  %head
    %title
      CareerPath
      = yield :title
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :style
    = javascript_include_tag 'application'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.3.1/css/all.css", :integrity => "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", :rel => "stylesheet"}/
  %body
    .container-fluid.main-container
      = yield